### ISSUE TITLE
Problem with WKDR on NYU dataset

### ISSUE THREAD

**Issue by ChenyangLiu** [umich-vl/relative_depth#4]
Hi,

I noticed that in your paper, Table 2, your WKDR is less than both WKDR_eq and WKDR_neq. But I think that, WKDR should be a weighted ave of them. How do you get the WKDR?

**Comment by wfchen-umich** [comment]
Hi, thank you for your interest in our paper. 
Please take a look at:
https://github.com/umich-vl/relative_depth/blob/master/src/experiment/test_model_on_NYU.lua

**Comment by wfchen-umich** [comment]
I think that is because we take the mean of WKDR from each image, but not calculating the WKDR of all the pairs as a whole.
