### ISSUE TITLE
About the loss funtion

### ISSUE THREAD

**Issue by Ariel-JUAN** [umich-vl/relative_depth#5]
Hi, thanks for sharing the great work. I try some Internet images and it works really well.
Can you tell me how to define closer and further in loss function? I am really confused.   
Thank  you！

**Comment by wfchen-umich** [comment]
Hi, if point A is further away than point B, then the label of rel_AB = 1. If A is at the same depth as B, then rel_AB = 0.

**Comment by Ariel-JUAN** [comment]
Thank you~

**Comment by nian-liu** [comment]
> Hi, if point A is further away than point B, then the label rel_AB = 1. If A is at the same depth as B, then rel_AB = 0; if point A is closer than point B, then the label rel_AB = -1.

Hi, It seems that it's a bit confusing for the description in the "Loss Function" section in the paper. It says "and r_k \in {+1,-1,0} is the ground-truth depth relation between i_k and j_k: closer (+1),
further (−1), and equal (0)" in this section. According to your reply and the loss function, "closer(+1)" should mean j_k is closer than i_k, and "further (−1)" means j_k is further away than i_k. But based on a direct understanding of this sentence, one is easy to treat "i_k" and "j_k" as the subject and the object, respectively, which leads to an inverse relation.
